#!/bin/sh -e

DIR="/usr/share/plantuml"

UNUSED_CONFIG="
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false
"

java -splash:no -jar $DIR/plantuml.jar \
    "$@"
