#!/bin/sh -e

DIR="/usr/share/plantuml"

CONFIG="
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false
"

java \
    -splash:no \
    -cp * net.sourceforge.plantuml.Run \
    -Shandwritten="true" \
    -Smonochrome="true" \
    -SpackageStyle="rect" \
    -SdefaultFontName="FG Virgil" \
    -Sshadowing="false" \
    "$@"
